export { default as AuthPage } from "./AuthPage/AuthPage"
export { default as ChatsPage } from "./ChatsPage/ChatsPage"
export { default as NavBar } from "./NavBar/NavBar"
export { default as Footer } from "./Footer/Footer"
export { default as Developercontact } from "./DeveloperContact/DeveloperContact"